# Generated by Django 3.2.12 on 2022-02-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approle',
            name='description',
            field=models.CharField(blank=True, help_text='Application Role Description', max_length=200),
        ),
        migrations.AlterField(
            model_name='orgrole',
            name='description',
            field=models.CharField(blank=True, help_text='Organization Role Description', max_length=200),
        ),
    ]
