# Generated by Django 3.2.12 on 2022-02-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('', 'Not Specified')], default='', help_text='Member Gender', max_length=1),
        ),
    ]
