# Generated by Django 3.2.12 on 2022-02-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_member_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='age_group',
            field=models.CharField(blank=True, choices=[(
                'SSE', 'SSE (4 - 18)'), ('YA', 'YA (18 - 40)'), ('Adult', 'Adult (40 +)'), ('', 'Not Specified')], default='', max_length=10),
        ),
    ]
