# Generated by Django 3.2.12 on 2022-02-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20220206_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='orgrole',
        ),
        migrations.AddField(
            model_name='member',
            name='orgrole',
            field=models.ManyToManyField(help_text='select organization role', to='website.OrgRole'),
        ),
    ]
