# Generated by Django 3.2.12 on 2022-02-16 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_member_age_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': (('is_authenticated', 'holds authentication'), ('can_view_links', 'can access links'), ('can_modify_member_data', 'to modify member data'))},
        ),
    ]
