# Generated by Django 3.2.12 on 2022-02-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20220207_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, help_text='Member Address', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(blank=True, help_text='Member Age'),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(blank=True, help_text="Member's OrgRole End Date"),
        ),
        migrations.AlterField(
            model_name='member',
            name='start_date',
            field=models.DateField(blank=True, help_text="Member's OrgRole Start Date"),
        ),
    ]
