# Generated by Django 3.2.12 on 2022-02-17 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_member_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': (('can_view_links', 'can access links'), ('can_modify_member_data', 'to modify member data'))},
        ),
    ]
