# Generated by Django 3.2.12 on 2022-02-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_member_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(blank=True, help_text="Member's OrgRole End Date", null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='start_date',
            field=models.DateField(blank=True, help_text="Member's OrgRole Start Date", null=True),
        ),
    ]
