# Generated by Django 3.2.12 on 2022-02-22 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_member_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['first_name'], 'permissions': (('is_central_officer', 'is central officer'), ('is_regional_officer', 'is regional officer'), ('is_national_officer', 'is national officer'))},
        ),
    ]
