# Generated by Django 3.2.12 on 2022-02-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20220207_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='approle',
            name='level',
            field=models.CharField(default='L1', help_text='access level', max_length=2),
        ),
    ]
