# Generated by Django 3.2.12 on 2022-02-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_member_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgrole',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
