# Generated by Django 3.2.12 on 2022-02-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_approle_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=600)),
            ],
        ),
    ]
