# Generated by Django 3.2.12 on 2022-02-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgrole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
