# Generated by Django 3.2.12 on 2022-02-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_center_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='center_type',
            field=models.CharField(choices=[('Center', 'Center'), ('Group', 'Group')], default='Center', help_text='Center centerType', max_length=10),
        ),
    ]
