# Generated by Django 3.2.12 on 2022-02-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_center_center_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Center Latitude', max_digits=30),
        ),
        migrations.AlterField(
            model_name='center',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Center Longitude', max_digits=30),
        ),
    ]
