# Generated by Django 3.2.12 on 2022-02-27 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20220227_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='address',
        ),
        migrations.RemoveField(
            model_name='center',
            name='center_type',
        ),
        migrations.RemoveField(
            model_name='center',
            name='city',
        ),
        migrations.RemoveField(
            model_name='center',
            name='country',
        ),
        migrations.RemoveField(
            model_name='center',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='center',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='center',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='center',
            name='region',
        ),
        migrations.RemoveField(
            model_name='center',
            name='state',
        ),
        migrations.RemoveField(
            model_name='center',
            name='status',
        ),
        migrations.RemoveField(
            model_name='center',
            name='website',
        ),
        migrations.RemoveField(
            model_name='center',
            name='zip_code',
        ),
    ]
